### ISSUE TITLE
[BUG] Select converts to input when no enum options

### ISSUE THREAD

**Issue by mishoboss** [naguvan/react-mst-form#4]
When there are no enum options, select field fallbacks to input field. Which is not okay (IMHO). This is the line that does this:
`const select: boolean = !!type.enum && type.enum.length > 0;`

I believe just a check `hasOwnProperty('enum')` is enough to determine if field should be of select type or input text.

**Comment by naguvan** [comment]
currently the type object would always have "enum" as own property. hence hasOwnProperty("enum" along can not fix the behaviour. could you please share the field config and specifying whether you expect "select" or "input" component?

currently working on the next major version where we have more control on which component to be selected.  string field type would support  "date", "select", "password" "text" etc. so we can explicitly specific which component to render. sample can be found in below link. let me know your thought on this.

https://naguvan.github.io/react-mst-form/packages/typescript-react-app-demo/src/index.html

**Comment by naguvan** [comment]
Issue is fixed in the current beta version [demo](https://naguvan.github.io/react-mst-form/packages/typescript-react-app-demo/src/index.html) 

[beta package](https://www.npmjs.com/package/react-mst-form/v/2.0.0-beta2)
