### ISSUE TITLE
Error text for enum is not good

### ISSUE THREAD

**Issue by mishoboss** [naguvan/react-mst-form#5]
Error text for enum select fields includes all the values available in the enum. If we have a select field with 100 values, the error message will be loooong...

Additionally, it uses the values, not option labels. Values are usually some hash IDs that don't have any meaningful value for the user.

![image](https://user-images.githubusercontent.com/1629929/46907819-1c45b180-cf21-11e8-86ac-45bae5220a91.png)

Can we just say "should be not empty"?

**Comment by naguvan** [comment]
The error for enum is matching the expected json-spec error. hence can not be avoided. But we can override the error message part of the form's field config inside meta tag. These changes are part of next major version. would like to discuss about it and get more feedback.

```js
{
      type: {
        meta: {
          error: "should not be empty",
          options: [
            { label: "One", value: 1 },
            { label: "Two", value: 2 },
            { label: "Three", value: 3 }
          ]
        },
        type: "number",
        title: "Select a type",
        enum: [1, 2, 3]
      }
}
```

you can check the behaviour below

https://naguvan.github.io/react-mst-form/packages/typescript-react-app-demo/src/index.html

**Comment by mishoboss** [comment]
Seems good to me :)

**Comment by naguvan** [comment]
Issue is fixed in the current beta version [demo](https://naguvan.github.io/react-mst-form/packages/typescript-react-app-demo/src/index.html) 

[beta package](https://www.npmjs.com/package/react-mst-form/v/2.0.0-beta2)
