### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by naguvan** [naguvan/react-mst-form#7]
TODO: need to update the progress and changes

1) Non Json-Schema properties to be moved to single complex property called "meta" (non-spec property)

From:
```js
{
 "password": {
    "type": "string",
    "component": "password",
    "minLength": 6,
    "maxLength": 20,
    "sequence": 2
 }
}
```
To:
```js
{
 "password": {
    "type": "string",
    "minLength": 6,
    "maxLength": 20,
     "meta": {
          "component": "password",
          "sequence": 2
     }
 }
}
```

2) Type specific "meta" properties with compile time check with typescript and runtime check with "mobx-state-tree"

3) more material-ui component support for type "string". ex: "date", "datetime", "password" etc

**Comment by mishoboss** [comment]
Please think about field icons. Now with the meta property that could be achieved there. I can think of two new properties in `meta`:
- `icon` - string representing some Material Icon
- `iconAlign` - align the icon left/right to the field (start/end)

https://material-ui.com/demos/text-fields/#with-icon

**Comment by naguvan** [comment]
Yes. i was also thinking about icons sometimes back. Thanks for the feedback. will incorporate part of 2.0.0 release.

**Comment by naguvan** [comment]
beta version [demo](https://naguvan.github.io/react-mst-form/packages/typescript-react-app-demo/src/index.html) with meta and with icon and iconAlign has been implemented.

[beta package](https://www.npmjs.com/package/react-mst-form/v/2.0.0-beta2)

please let me know if you could try and provide feedback. would release the build soon.
