### ISSUE TITLE
[BUG] Number field can't accept value of 0

### ISSUE THREAD

**Issue by mikepanayotov** [naguvan/react-mst-form#8]
Number field can't accept value of 0

```
type: 'number',
value: 0,
maximum: 100,
minimum: 0
```

![image](https://user-images.githubusercontent.com/42741550/47605522-321ea080-da10-11e8-8250-09a17868023f.png)

**Comment by naguvan** [comment]
thanks for reporting. will fix it.

**Comment by naguvan** [comment]
Issue is fixed in the current beta version [demo](https://naguvan.github.io/react-mst-form/packages/typescript-react-app-demo/src/index.html) [npm](https://www.npmjs.com/package/react-mst-form/v/2.0.0-beta2)

**Comment by naguvan** [comment]
Issue is fixed in the current beta version [demo](https://naguvan.github.io/react-mst-form/packages/typescript-react-app-demo/src/index.html) 

[beta package](https://www.npmjs.com/package/react-mst-form/v/2.0.0-beta2)
